### ISSUE TITLE
Question about refId

### ISSUE THREAD

**Issue by NeoDigi** [TouK/kotlin-exposed-realworld#1]
Hello and thanks for this repo.
I've been using it as a template for an app that I'm building.
I have a question about the refId, it work extremely well when you're creating every object yourself but how would you manage when you have an object that already have an ID when arriving on the backend ? 

Because of:
```val id: ArticleId = ArticleId.New``` 
This will fail any deserialization that come from the front end that already have an id

Thanks in advance

**Comment by pjagielski** [comment]
Hi, good to hear it's useful.
Regarding the question, I need some more info: as I understand you need to store identifier from external system and use it as foreign key between tables? If so - indeed, our refId's are designed for DB auto-generated values. But I think you'll just need a custom wrapped implementation:
```kotlin
data class MyId(val external: Long)


fun Table.myId(columnName: String): Column<MyId> = longWrapper<MyId>(columnName, ::MyId, MyId::external)
```

Is this helpful?

**Comment by NeoDigi** [comment]
Not quite:
let's say I have the table article, the same as in the project:
(skipped some field for clarity)
```kotlin
object ArticleTable : Table("articles") {
    val id = articleId("id").primaryKey().autoIncrement()
    val title = text("title")
}
```
Of course the val id, in my case, is not autoIncremented.
Here, as you say it works fine because the id will be autogenerated but let say that when someone create an article on the frontend, it comes with an Id, so when you received the call it will be something like:

```json
{
    "id": "132323",
    "title": "test article"
}
```

In a perfect world I would still want to use the refId, or something similar when I create this object.
Unfortunately I couldn't really find a solution that I liked yet

**Comment by pjagielski** [comment]
Ok so you mean deserializing RefId from JSON using Jackson?
If so, maybe using dedicated `@JsonCreator` constructor in `Article`  may help?
```kotlin
    @JsonCreator
    constructor(@JsonProperty("id") id: Long, @JsonProperty("title") title: String) : this(ArticleId.Persisted(id), title)
```

**Comment by NeoDigi** [comment]
Thank you for your answer
I actually try something very similar using Gson and I ended with this error:

> Database value ArticleId(value=5642aef948e51025cf4a7a99) of class com.example.utils.refs.ArticleId.Persisted is not valid class kotlin.String

The error is from here: https://github.com/TouK/kotlin-exposed-realworld/blob/4be448373f8df29395c2ea4634129e3c4d4ccf47/src/main/kotlin/io/realworld/shared/infrastructure/WrapperColumn.kt#L67

I did just tried the same thing again with Jackson but ended up with the exact same result.
And that's basically where I'm stuck ...

**Comment by pjagielski** [comment]
Maybe you can provide some minimal example project showing this issue, that we can analyze?

**Comment by NeoDigi** [comment]
@pjagielski hey, here is a fork that will will with the same error message that I have when trying to create a new article with an ID already decided:
https://github.com/NeoDigi/kotlin-exposed-realworld

The error is:

> Database value ArticleId(value=34) of class io.realworld.shared.refs.ArticleId.Persisted is not valid class kotlin.Long

You can look at the last commit to see what I changed:
https://github.com/NeoDigi/kotlin-exposed-realworld/commit/a43623e797eeb72f488289b2c3fe89c299988a5b

I updated the test too and it's failing as it should right now.
And an example json to send to the post /articles endpoint:
```json
{"article":{"id": 34, "title":"How to train your dragon", "description":"Ever wonder how?", "body":"Very carefully.", "tagList":["dragons","training"]}}
```

If you need more information let me know.
I had to remove the 
```kotlin
@GeneratedValue
```
annotation otherwise the from extension would not copy the id (and we want to copy it)
```kotlin
fun UpdateBuilder<Any>.from(article: Article) {
  	this[ArticleTable.id] = article.id // this line
  	this[ArticleTable.title] = article.title
  	this[ArticleTable.slug] = article.slug
  	this[ArticleTable.description] = article.description
  	this[ArticleTable.body] = article.body
  	this[ArticleTable.authorId] = article.authorId
  	this[ArticleTable.createdAt] = article.createdAt
  	this[ArticleTable.updatedAt] = article.updatedAt
}
``` 

but if you take the project before the latest merge when the extension was not generated yet, the error would be the same.
also on my project I could actually make it work by changing:
https://github.com/TouK/kotlin-exposed-realworld/blob/4be448373f8df29395c2ea4634129e3c4d4ccf47/src/main/kotlin/io/realworld/shared/infrastructure/WrapperColumn.kt#L43

to

```kotlin
class LongWrapperColumnType<out Wrapper : Any>(
    wrapperClazz: KClass<Wrapper>,
    instanceCreator: (Long) -> Wrapper,
    valueExtractor: (Wrapper) -> Long
) : WrapperColumnType<Long, Wrapper>(LongColumnType(), Long::class, wrapperClazz, instanceCreator, valueExtractor) {

    override fun valueFromDB(value: Any) = when (value) {
        is Long -> instanceCreator(rawColumnType.valueFromDB(value) as Long)
        is Int -> instanceCreator(rawColumnType.valueFromDB(value) as Long)
        is ArticleId.Persisted -> instanceCreator(rawColumnType.valueFromDB(value.value) as Long) // added this line
        is BigDecimal -> instanceCreator(rawColumnType.valueFromDB(value) as Long)
        else -> error("Database value $value of class ${value::class.qualifiedName} is not valid $rawClazz")
    }
}
```

But I don't think that's a very good solution.
If you have any more question I would be glad to help.

**Comment by pjagielski** [comment]
Thanks! Looks like we have a bug in our generator - we try to act like there was @GeneratedValue present. I'll let you know about the fix.

**Comment by NeoDigi** [comment]
Hmm I'm not sure the issue is in the generator to be honest, because with @GeneratedValue the id field is not there which is correct and without it the id field is there so that's also correct.

I think the issue is (and I'm really not sure) but when creating an id with ArticleId.New when we get inside the LongWrapperColumnType, the value type is indeed a Long but when creating an id with ArticleId.persisted(id)  when we reach the LongWrapperColumnType, the value is not a Long but an ArticleId.Persisted
I feel like it shouldn't matter if I create an id with new or persisted the type should be Long.

I feel the magic of unwrapping the value happen here:
```kotlin
override val value: Long by IdNotPersistedDelegate<Long>()
 ```

But to be honest i didn't really work with Delegate and I'm not really understanding how they work.

Again this is just my guess, I might be totally wrong.

**Comment by pjagielski** [comment]
I managed to reproduce the bug and I release fix in our library for this. Could you please upgrade in your `build.gradle/pom.xml` the version of `krush` to `0.2.0`. 
You'll also have to remove reference to our `@Convert` annotation in favor of `javax.persistence` version - see this commit https://github.com/TouK/kotlin-exposed-realworld/commit/6b4bd846c6ff89fa80c4748b688e6a28a93684be

**Comment by NeoDigi** [comment]
Hey, thank for this but unfortunately the test is still failing:
Here you can the change I made to the test `should save article`:
https://github.com/NeoDigi/kotlin-exposed-realworld/blob/a43623e797eeb72f488289b2c3fe89c299988a5b/src/test/kotlin/io/realworld/article/domain/ArticleServiceIntegrationTest.kt#L59

I added this line:
```kotlin
 assertThat(id).isEqualTo(createArticleDto.id)
```

But I ended up with the same error as before:
Database value ArticleId(value=81446) of class io.realworld.shared.refs.ArticleId.Persisted is not valid class kotlin.Long

**Comment by pjagielski** [comment]
Did you upgrade to krush 0.2.0? I can't see it - look at this PR: https://github.com/NeoDigi/kotlin-exposed-realworld/pull/1 - it should work now

**Comment by NeoDigi** [comment]
I did upgrade before testing (on my local branch) but even with your merge the test is still failing with the same error.
is it working on your side ?

**Comment by pjagielski** [comment]
Yes it works on my fork
